### PR TITLE
Update NetSalary.c

### PR DESCRIPTION
**Pull request by harshitgupta028**
I have made changes please check and merge my changes.

Also, please add the tag "hacktoberfest-accepted"

### CODE REVIEW

**Comment by sugandha-kadp** [comment]
please check it has so many mistakes.

**Comment by harshitgupta028** [comment]
Please check now, I think now it is good.

**Comment by harshitgupta028** [comment]
Also, you have written all code in c++ but the extension of the file is c so, I have changed that also.

**Comment by sugandha-kadp** [comment]
all are correct, but switch statement has a problem.

**Comment by Sugandha-kadp** [comment]
all are correct, but switch statement has a problem.

**Comment by harshitgupta028** [comment]
okay, Let me check once again.

**Comment by harshitgupta028** [comment]
Please check it now.
Also, please add the tag "hacktoberfest-accepted"

**Review by sugandha-kadp — COMMENTED** [review]
Done

**Pull request closed without merging**
